cundinas/contributors/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'contributors'
urlpatterns = [
  path('<int:pk>/', views.ContributorList.as_view(), name='contributor_list'),
  path('create/', views.ContributorCreate.as_view(), name='contributor_create'),
  path('update_amount/<int:cunpk>/<int:pk>/', views.ContributorUpdateAmount.as_view(), name='contributor_update_amount'),
]

cundinas/cundinas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('cundinas/', include('cundinasapp.urls')),
    path('contributors/', include('contributors.urls')),
    path('admin/', admin.site.urls),
]

cundinas/cundinasapp/urls.py
from django.urls import path
from . import views

app_name = 'cundinas'
urlpatterns = [
  path('', views.CundinaList.as_view(), name='cundina_list'),
  path('create/', views.CundinaCreate.as_view(), name='cundina_create'),
]

cundinas/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'
urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('login/', auth_views.LoginView.as_view(template_name='home/login.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.Signup.as_view(), name='signup'),
]

cundinas/contributors/models.py
from django.db import models
from cundinasapp.models import Cundina

class Contributor(models.Model):
  name = models.CharField(max_length=250)
  amount = models.DecimalField(max_digits=7, decimal_places=2)
  total_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
  cundina = models.ForeignKey(Cundina, on_delete=models.CASCADE, related_name='contributors')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
      return self.name

  class Meta:
    ordering = ['-created_at',]

cundinas/cundinasapp/models.py
from django.db import models

class Cundina(models.Model):
  goal = models.DecimalField(max_digits=7, decimal_places=2)
  current_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f"Cundina #{self.id}"

  class Meta:
    verbose_name = "Cundina"
    verbose_name_plural = "Cundinas"

cundinas/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

class SavingManager(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  def __str__(self):
      return self.user.username

@receiver(post_save, sender=User)
def ensure_savingmanager_exists(sender, instance, **kwargs):
  if kwargs.get('created', False):
    SavingManager.objects.get_or_create(user=instance)

cundinas/contributors/forms.py
from django import forms
from .models import Contributor

class ContributorForm(forms.ModelForm):
  amount = forms.DecimalField(min_value=0)

  class Meta:
    model = Contributor
    fields = ['name', 'amount','cundina',]

cundinas/cundinasapp/forms.py
from django import forms
from .models import Cundina

class CundinaForm(forms.ModelForm):
  # goal = forms.DecimalField(max_digits=7, decimal_places=2)

  class Meta:
    model = Cundina
    fields = ['goal',]

cundinas/contributors/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import Contributor
from cundinasapp.models import Cundina
from .forms import ContributorForm
from django.contrib.auth.mixins import LoginRequiredMixin

class ContributorList(LoginRequiredMixin, generic.ListView):
  model = Contributor
  template_name = 'contributors/contributor_list.html'

  def get_queryset(self):
    cundina = get_object_or_404(Cundina, id=self.kwargs['pk'])
    return Contributor.objects.filter(cundina=cundina).order_by('-created_at')

class ContributorCreate(LoginRequiredMixin, generic.CreateView):
  model = Contributor
  form_class = ContributorForm
  template_name = 'contributors/contributor_form.html'

  def get_success_url(self):
    return self.request.path

class ContributorUpdateAmount(LoginRequiredMixin, generic.RedirectView):
  def get_redirect_url(self, *args, **kwargs):
    contributor = get_object_or_404(Contributor, pk=kwargs['pk'])
    contributor.total_amount += contributor.amount
    contributor.save()

    cundina = get_object_or_404(Cundina, pk=contributor.cundina.id)
    cundina.current_amount += contributor.amount
    cundina.save()

    return reverse('contributors:contributor_list', args=(kwargs['cunpk'],))
    # return super().get_redirect_url(*args, **kwargs)

cundinas/cundinasapp/views.py
from django.shortcuts import render
from .models import Cundina
from django.views import generic
from django.urls import reverse_lazy, reverse
from .forms import CundinaForm
from django.contrib.auth.mixins import LoginRequiredMixin

class CundinaList(LoginRequiredMixin, generic.ListView):
  model = Cundina
  template_name = 'cundinasapp/cundina_list.html'

# class CundinaDetail(generic.DetailView):
#   model = Cundina
#   template_name = 'cundinasapp/cundina_detail.html'

class CundinaCreate(LoginRequiredMixin, generic.CreateView):
  model = Cundina
  form_class = CundinaForm
  template_name = 'cundinasapp/cundina_form.html'
  success_url = reverse_lazy('cundinas:cundina_list')

cundinas/home/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class Home(generic.TemplateView):
  template_name = 'home/home.html'

class Signup(generic.CreateView):
  template_name = 'home/signup.html'
  form_class = UserCreationForm
  success_url = reverse_lazy('home:login')

cundinas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %} | Cundinas</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:home' %}">Cundinas</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'home:home' %}">Home</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'cundinas:cundina_list' %}">Cundinas</a>
            {% comment %} <a class="nav-item nav-link" href="{% url 'articles:category_list' %}">Categories</a> {% endcomment %}
            <a class="nav-item nav-link" href="{% url 'home:logout' %}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'home:login' %}">Log In</a>
            <a class="nav-item nav-link" href="{% url 'home:signup' %}">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  
  <div class="container mt-5">
    {% block content %}{% endblock %}
  </div>

  <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

  {% block scripts %}{% endblock %}
</body>
</html>

cundinas/templates/contributors/contributor_form.html
{% extends 'base.html' %}

{% block title %}Save contributor{% endblock title %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}

    <div class="form-group">
      <button type="submit" class="btn btn-dark">Save</button>
    </div>
  </form>
{% endblock %}

cundinas/templates/contributors/contributor_list.html
{% extends 'base.html' %}

{% block title %}Contributor list{% endblock title %}

{% block content %}
  {% if contributor_list %}
    <a href="{% url 'contributors:contributor_create'  %}?next={{ request.get_full_path }}" class="btn btn-dark">Add contributor</a>
    <br />
    <br />
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Total amount</th>
          <th scope="col">Add amount</th>
        </tr>
      </thead>
      <tbody>
        {% for contributor in contributor_list %}
          <tr>
            <td>{{ contributor.name }}</td>
            <td>$ {{ contributor.total_amount }}</td>
            <td><a href="{% url 'contributors:contributor_update_amount' contributor.cundina.id contributor.id %}" class="btn btn-dark">Add amount</a></td>
          </tr>
          {% if forloop.last %}
            <tr>
              <td>Total</td>
              <td>$ {{ contributor.cundina.current_amount }}</td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="text-center">
      No contributors yet
      <br />
      <br />
      <a href="{% url 'contributors:contributor_create' %}" class="btn btn-primary">Create one</a>
    </div>
  {% endif %}
{% endblock %}

cundinas/templates/cundinasapp/cundina_form.html
{% extends 'base.html' %}

{% block title %}Save cundina{% endblock title %}

{% block content %}
  <h2>Create cundina</h2>
  <hr />
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-group">
      <button type="submit" class="btn btn-dark">Save</button>
    </div>
  </form>
{% endblock %}

cundinas/templates/cundinasapp/cundina_list.html
{% extends 'base.html' %}

{% block title %}Contributor list{% endblock title %}

{% block content %}
  {% if cundina_list %}
    <h2>Cundina list</h2>
    <hr />
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Total amount</th>
        </tr>
      </thead>
      <tbody>
        {% for cundina in cundina_list %}
          <tr>
            <td><a href="{% url 'contributors:contributor_list' cundina.id %}" class="text-decoration-none">Cundina #{{ cundina.id }}</a></td>
            <td>$ {{ cundina.current_amount }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="text-center">
      No cundinas yet
      <br />
      <br />
      <a href="{% url 'cundinas:cundina_create' %}" class="btn btn-primary">Create one</a>
    </div>
  {% endif %}
{% endblock %}

cundinas/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="text-center">
    <h3>Welcome to Cundinas App</h3>
  </div>
{% endblock %}

cundinas/templates/home/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Log In{% endblock %}

{% block content %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {{ error }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}

  <div class="row justify-content-center">
    <div class="col-4">
      <h2 class="text-center">Log In</h2>
      <hr />

      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          {{ form.username|attr:"class:form-control"|attr:"placeholder:Username"|attr:"autofocus" }}
        </div>

        <div class="form-group">
          {{ form.password|attr:"class:form-control"|attr:"placeholder:Password" }}
        </div>

        <div class="form-group text-center">
          <button class="btn btn-primary mr-2" type="submit">Log In</button>
          <a class="btn" href="{% url 'home:signup' %}">I need an account</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

cundinas/templates/home/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-4">
      <h2 class="text-center">Sign Up</h2>
      <hr />
    
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          {{ form.username|attr:"class:form-control"|attr:"placeholder:Username"|attr:"autofocus" }}
          {% for error in form.username.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
              {{ error }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>
        
        <div class="form-group">
          {{ form.password1|attr:"class:form-control"|attr:"placeholder:Password" }}
          {% for error in form.password1.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
              {{ error }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>

        <div class="form-group">
          {{ form.password2|attr:"class:form-control"|attr:"placeholder:Confirm your password" }}
          {% for error in form.password2.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
              {{ error }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>

        <div class="form-group text-center">
          <button class="btn btn-primary mr-2" type="submit">Register</button>
          <a class="btn" href="{% url 'home:login' %}">I already have an account</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}