art_galery/art_galery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('articles/', include('articles.urls', namespace='articles')),
    path('authors/', include('authors.urls', namespace='authors')),
    path('admin/', admin.site.urls),
]

art_galery/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
  path('', views.ArticleList.as_view(), name='article_list'),
  path('<int:pk>/', views.ArticleDetail.as_view(), name='article_detail'),
  path('create/', views.ArticleCreate.as_view(), name='article_create'),
  path('update/<int:pk>/', views.ArticleUpdate.as_view(), name='article_update'),
  path('delete/<int:pk>/', views.ArticleDelete.as_view(), name='article_delete'),
  path('categories/', views.CategoryList.as_view(), name='category_list'),
  path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category_detail'),
]

art_galery/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'
urlpatterns = [
  path('', views.AuthorList.as_view(), name='author_list'),
  path('<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
]

art_galery/home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'home'
urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('login/', auth_views.LoginView.as_view(template_name="home/login.html"), name="login"),
  path('logout/', auth_views.LogoutView.as_view(template_name="home/login.html"), name="logout"),
  path('signup/', views.Signup.as_view(), name='signup'),
]

art_galery/articles/models.py
from django.db import models
from authors.models import Author
class Category(models.Model):
  name = models.CharField(max_length=100)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta:
    verbose_name_plural = 'categories'
    ordering = ['name']
  
  def __str__(self):
    return self.name

class Article(models.Model):
  title = models.CharField(max_length=200)
  content = models.TextField()
  author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='get_articles')
  categories = models.ManyToManyField(Category, related_name='get_articles')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta:
    ordering = ['-created_at']
  
  def __str__(self):
    return self.title

art_galery/authors/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  def __str__(self):
      return self.user.username
  

art_galery/home/models.py
from django.db import models
from django.contrib.auth.models import User
from authors.models import Author
from django.dispatch import receiver
from django.db.models.signals import post_save

@receiver(post_save, sender=User)
def ensure_author_exists(sender, instance, **kwargs):
  if kwargs.get('created', False):
    Author.objects.get_or_create(user=instance)

art_galery/articles/forms.py
from django import forms
from .models import Article, Category

class ArticleForm(forms.ModelForm):
  title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': True}))
  content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}))

  class Meta:
    model = Article
    fields = ['title', 'content', 'categories',]

art_galery/articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Article, Category
from django.urls import reverse_lazy
from django.views import generic
from authors.models import Author
from .forms import ArticleForm

# Articles
class ArticleList(LoginRequiredMixin, generic.ListView):
  model = Article

class ArticleDetail(LoginRequiredMixin, generic.DetailView):
  model = Article

class ArticleCreate(LoginRequiredMixin, generic.CreateView):
  model = Article
  form_class = ArticleForm
  success_url = reverse_lazy('articles:article_list')

  def form_valid(self, form):
    author = Author.objects.get(user=self.request.user)
    form.instance.author = author
    return super().form_valid(form)

class ArticleUpdate(LoginRequiredMixin, generic.UpdateView):
  model = Article
  form_class = ArticleForm
  success_url = reverse_lazy('articles:article_list')

class ArticleDelete(LoginRequiredMixin, generic.DeleteView):
  model = Article
  success_url = reverse_lazy('articles:article_list')

# Categories
class CategoryList(LoginRequiredMixin, generic.ListView):
  model = Category

class CategoryDetail(LoginRequiredMixin, generic.DetailView):
  model = Category

art_galery/authors/views.py
from django.views import generic
from .models import Author
from articles.models import Article
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

class AuthorList(LoginRequiredMixin, generic.ListView):
  model = Author

class AuthorDetail(LoginRequiredMixin, generic.DetailView):
  model = Author

art_galery/home/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class Home(generic.TemplateView):
  template_name = 'home/home.html'

class Signup(generic.CreateView):
  template_name = 'home/signup.html'
  form_class = UserCreationForm
  success_url = reverse_lazy('home:login')

art_galery/templates/articles/article_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete article{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-header">
          Delete article
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}

            <p>Are you sure you want to delete "{{ article.title }}"?</p>

            <a href="{% url 'articles:article_list' %}" class="btn btn-secondary mr-2">No</a>
            <button type="submit" class="btn btn-danger">Yes, delete it</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

art_galery/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock title %}

{% block content %}
  <blockquote class="blockquote text-center">
    <h3 class="mb-0">{{ article.title }}</h3>
    <footer class="blockquote-footer">By <cite>{{ article.author.user.username }}</cite></footer>
  </blockquote>
  <div class="row justify-content-center">
    {% for category in article.categories.all %}
      <a href="{% url 'articles:category_detail' category.id %}" class="badge badge-success mr-2">{{category.name}}</a>
    {% endfor %}
  </div>
  <hr />

  <p>{{ article.content }}</p>

  {% if article.author.user.id == user.id %}
    <a href="{% url 'articles:article_update' article.id %}" class="btn btn-warning">Update</a>
    <a href="{% url 'articles:article_delete' article.id %}" class="btn btn-danger">Delete</a>
  {% endif %}
{% endblock content %}

art_galery/templates/articles/article_form.html
{% extends 'base.html' %}

{% block title %}Save article{% endblock %}

{% block content %}
  <h2>Save article</h2>
  <hr />

  <div class="row">
    <div class="col-4">
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          {{ form.as_p }}
        </div>

        <div class="form-group">
          <a class="btn" href="{% url 'articles:article_list' %}">Cancel</a>
          <button class="btn btn-primary mr-2" type="submit">Save</button>
        </div>
      </form>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script>
    let id_categories = document.querySelector('#id_categories');

    id_categories.className += 'selectpicker';
  </script>
{% endblock %}

art_galery/templates/articles/article_list.html
{% extends 'base.html' %}

{% block title %}Article list{% endblock %}

{% block content %}
  {% if not article_list %}
    <div class="text-center">
      <h3>No articles yet</h3>
      <a class="btn" href="{% url 'articles:article_create' %}">Create one</a>
    </div>
    {% else %}
    <div class="row">
      <h2>Article list</h2>
      <a class="btn btn-primary ml-auto" href="{% url 'articles:article_create' %}">Create article</a>
    </div>
    <br />

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Category</th>
          <th scope="col">Published</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for article in article_list %}
          <tr>
            <td>
              <a href="{% url 'articles:article_detail' article.id %}" class="h5 text-decoration-none">{{ article.title }}</a>
            </td>
            <td>
              {% for category in article.categories.all %}
                <a href="{% url 'articles:category_detail' category.id %}" class="text-decoration-none">{{category.name}}</a>{% if not forloop.last %},{% endif %}
              {% endfor %}
            </td>
            <td>{{ article.created_at|date:"jS \o\f F\, Y" }}</td>
            <td>
              {% if article.author.user.id == user.id %}
                <a href="{% url 'articles:article_update' article.id %}" class="btn btn-warning">Update</a>
                <a href="{% url 'articles:article_delete' article.id %}" class="btn btn-danger">Delete</a>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock %}

art_galery/templates/articles/category_detail.html
{% extends 'base.html' %}

{% block title %}{{ category.name }} category{% endblock title %}

{% block content %}
  <h2 class="text-center">{{ category.name }} category</h2>
  <hr />

  {% if category.get_articles %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Published</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for article in category.get_articles.all %}
          <tr>
            <td>
              <a href="{% url 'articles:article_detail' article.id %}" class="h5 text-decoration-none">{{ article.title }}</a>
            </td>
            <td>{{ article.created_at|date:"jS \o\f F\, Y" }}</td>
            <td>
              <a href="{% url 'articles:article_update' article.id %}" class="btn btn-warning">Update</a>
              <a href="{% url 'articles:article_delete' article.id %}" class="btn btn-danger">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="text-center">
      <h3>No articles yet</h3>
      <a class="btn" href="{% url 'articles:article_create' %}">Create one</a>
    </div>
  {% endif %}
{% endblock content %}

art_galery/templates/articles/category_list.html
{% extends 'base.html' %}

{% block title %}Category list{% endblock %}

{% block content %}
  <div class="row">
    <h2>Category list</h2>
    <a class="btn ml-auto" href="{% url 'articles:article_list' %}">Article list</a>
  </div>
  <br />

  {% if not category_list %}
    <div class="text-center">
      <h3>No categories yet</h3>
    </div>
    {% else %}
      <ul class="list-group list-group-flush">
        {% for category in category_list %}
          <li class="list-group-item">
            <a href="{% url 'articles:category_detail' category.id %}" class="text-decoration-none h4">{{ category.name }}</a>
          </li>
        {% endfor %}
      </ul>
  {% endif %}
{% endblock %}

art_galery/templates/authors/author_detail.html
{% extends 'base.html' %}

{% block title %}{{ author.user.username }}{% endblock title %}

{% block content %}
  <h2 class="text-center">{{ author.user.username }}</h2>
  <hr />

  {% if author.get_articles %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Published</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for article in author.get_articles.all %}
          <tr>
            <td>
              <a href="{% url 'articles:article_detail' article.id %}" class="h5 text-decoration-none">{{ article.title }}</a>
            </td>
            <td>{{ article.created_at|date:"jS \o\f F\, Y" }}</td>
            {% if author.user.id == user.id %}
              <td>
                <a href="{% url 'articles:article_update' article.id %}" class="btn btn-warning">Update</a>
                <a href="{% url 'articles:article_delete' article.id %}" class="btn btn-danger">Delete</a>
              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <div class="text-center">
      <h4>No articles yet</h4>
      {% if author.user.id == user.id %}
        <a href="{% url 'articles:article_create' %}" class="btn">Create one</a>
      {% endif %}
    </div>
  {% endif %}
{% endblock content %}

art_galery/templates/authors/author_list.html
{% extends 'base.html' %}

{% block title %}Author list{% endblock %}

{% block content %}
  <h2>Author list</h2>
  <br />

  {% if not author_list %}
    <div class="text-center">
      <h3>No authors yet</h3>
    </div>
    {% else %}
      <ul class="list-group list-group-flush">
        {% for author in author_list %}
          <li class="list-group-item">
            <a href="{% url 'authors:author_detail' author.id %}" class="text-decoration-none h4">{{ author.user.username }}</a>
          </li>
        {% endfor %}
      </ul>
  {% endif %}
{% endblock %}

art_galery/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %} | Art Galery</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-select/css/bootstrap-select.min.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:home' %}">Art Galery</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'home:home' %}">Home</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'articles:article_list' %}">Articles</a>
            <a class="nav-item nav-link" href="{% url 'articles:category_list' %}">Categories</a>
            <a class="nav-item nav-link" href="{% url 'authors:author_list' %}">Authors</a>
            <a class="nav-item nav-link" href="{% url 'home:logout' %}">Logout</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'home:login' %}">Log In</a>
            <a class="nav-item nav-link" href="{% url 'home:signup' %}">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  
  <div class="container mt-5">
    {% block content %}{% endblock %}
  </div>

  <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'popper.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap-select/js/bootstrap-select.min.js' %}"></script>

  {% block scripts %}{% endblock %}
</body>
</html>

art_galery/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="text-center">
    <h3>Welcome to Art Galery</h3>
  </div>
{% endblock %}

art_galery/templates/home/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Log In{% endblock %}

{% block content %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {{ error }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}

  <div class="row justify-content-center">
    <div class="col-4">
      <h2 class="text-center">Log In</h2>
      <hr />

      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          {{ form.username|attr:"class:form-control"|attr:"placeholder:Username"|attr:"autofocus" }}
        </div>

        <div class="form-group">
          {{ form.password|attr:"class:form-control"|attr:"placeholder:Password" }}
        </div>

        <div class="form-group text-center">
          <button class="btn btn-primary mr-2" type="submit">Log In</button>
          <a class="btn" href="{% url 'home:signup' %}">I need an account</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

art_galery/templates/home/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-4">
      <h2 class="text-center">Sign Up</h2>
      <hr />
    
      <form method="post">
        {% csrf_token %}

        <div class="form-group">
          {{ form.username|attr:"class:form-control"|attr:"placeholder:Username"|attr:"autofocus" }}
          {% for error in form.username.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
              {{ error }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>
        
        <div class="form-group">
          {{ form.password1|attr:"class:form-control"|attr:"placeholder:Password" }}
          {% for error in form.password1.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
              {{ error }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>

        <div class="form-group">
          {{ form.password2|attr:"class:form-control"|attr:"placeholder:Confirm your password" }}
          {% for error in form.password2.errors %}
            <div class="alert alert-danger alert-dismissible fade show mt-1" role="alert">
              {{ error }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>

        <div class="form-group text-center">
          <button class="btn btn-primary mr-2" type="submit">Register</button>
          <a class="btn" href="{% url 'home:login' %}">I already have an account</a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}